# Generated by Django 4.0.4 on 2022-05-26 22:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('estado_civil', models.CharField(choices=[('SL', 'Solteiro'), ('CS', 'Casado'), ('DV', 'Divorciado'), ('UE', 'União Estável'), ('NI', 'Não informado')], default='NI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7)),
                ('chassi', models.CharField(max_length=17)),
                ('ano_modelo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2099)])),
                ('alienado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Código')),
                ('seguradora', models.CharField(choices=[('BR', 'Bradesco'), ('PS', 'Porto Seguro'), ('AZ', 'Azul Seguros'), ('MA', 'Mapfre'), ('SA', 'Santander'), ('TM', 'Tokio Marine'), ('AL', 'Allianz')], max_length=2)),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('premio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prêmio Líquido')),
                ('perc_comissao', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Percentual Comissão')),
                ('segurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.segurado')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguros.veiculo')),
            ],
        ),
    ]
